version: "3.9"

services:
  mongo-main:
    image: mongo:4.4
    container_name: mongo-main
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-main-data:/data/db
    networks:
      - micro-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo-main:27017
    depends_on:
      - mongo-main
    networks:
      - micro-net

volumes:
  mongo-main-data:

networks:
  micro-net:
    driver: bridge
